### PR TITLE
Slight test tweaks

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Mostly reduces flushing in test.cpp

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
I'm on merging this

**Comment by nabijaczleweli** [comment]
This is good to go now

**Comment by tapio** [comment]
There were some things I didn't like, such as empty line before the blinking cursor that waits for anykey, so I manually picked other things from this PR. Still left is the `\n` vs. `endl`, but I'm not sure if it's worth it. In many cases, \n causes flush anyway, and regardless, it's not an performance issue here.

**Comment by nabijaczleweli** [comment]
Very well, very well

**Pull request closed without merging**
