### PR TITLE
Use WinAPI functions instead of system("cls") in cls()

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Adapted from [Microsoft's article on clearing the screen.](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682022%28v=vs.85%29.aspx)

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Could you at least put a comment like `// This clears the screen`?

**Comment by nabijaczleweli** [comment]
@kirbyfan64 Is the newest commit what you mean?

**Comment by kirbyfan64** [comment]
Ack, nevermind. I was stupid and completely missed the function comment itself.

**Comment by nabijaczleweli** [comment]
Okay, reverted

**Comment by nabijaczleweli** [comment]
@tapio Anything holding this back?

**Comment by tapio** [comment]
Hi, not merged yet because I haven't had the time to test this yet (I should also take care of the rest of the outstanding PRs at the same time). I'd also like to do a little benchmark to see if there is any benefits to doing it this way, since it makes the function a lot more complicated and I'm not sure anymore how much cheating the `system` call is, as MS itself includes it in their documentation.

**Comment by nabijaczleweli** [comment]
Calling `system()` is usually a bad idea, as is shelling off in general.
Of course there's a performance improvement - you don't launch 2/3 additional processes (which might also give warnings by some firewalls).

**Comment by nabijaczleweli** [comment]
Cheers

**Pull request merged**
